[LJI-4] Manual to run project locally
Java-POT-Summer-24/pot-java-summer-24 pull request #10
Opened 2024-06-17 16:54 UTC by NormantasN

Removed redundant dependencies and configurations, changed config from postgres to H2

2024-06-18 07:03 UTC, anton-kolyaev requested changes

2024-06-18 07:03 UTC, anton-kolyaev commented on src/main/resources/db/changelog/changelog-master.xml
> +<databaseChangeLog
Please move each changeset to it's own file and keep root one only to include files. 
https://docs.liquibase.com/change-types/include.html

2024-06-19 06:23 UTC, anton-kolyaev requested changes

2024-06-19 06:23 UTC, anton-kolyaev commented on src/main/resources/db/changelog/changelog-1.xml
1. do we need it at all in this commit?
2. please follow filenaming template as here
https://github.com/Java-POT-Summer-24/pot-java-summer-24/pull/8/files#diff-e42ff0f1696d9ae282dde9fb16962b555d9c4c940e435315916046a4ac8a54d7

2024-06-19 07:29 UTC, NormantasN commented on src/main/resources/db/changelog/changelog-1.xml
Done

2024-06-19 07:30 UTC, NormantasN commented on src/main/resources/db/changelog/changelog-master.xml
> +<databaseChangeLog
Done

2024-06-19 07:31 UTC, NormantasN commented on build.gradle
> +	testImplementation group: 'com.h2database', name: 'h2', version: '1.3.148'
Done

2024-06-19 08:04 UTC, SavaLX approved these changes

2024-06-19 08:08 UTC, anton-kolyaev approved these changes
resolve conflicts and you're welcome to merge it

2024-06-19 09:42 UTC, merged