Feature/LJI-5-company-mvc
Java-POT-Summer-24/pot-java-summer-24 pull request #11
Opened 2024-06-18 13:11 UTC by HotoMazur

LJI-5 task. Create the company mvc, mapper and dto. Add liquibase script to create and add data to table. Add unit and integration test by company.

2024-06-18 15:58 UTC, anton-kolyaev requested changes

2024-06-18 15:58 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
as you are adding controller for companies then you need not in ExampleController any more

2024-06-18 15:58 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/CompanyController.java
Exception hadnling? https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc#using-controlleradvice-classes

2024-06-18 15:58 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/dto/CompanyDTO.java
> +@Getter
You can replace some of that with `@Data` or `@Value` and add `@Builder` please
www.javabyexamples.com/lombok-data-and-value-for-fast-pojos

2024-06-18 15:58 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +    @Column()
I guess we need not in brackets over here (and futher)

2024-06-18 17:03 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/controller/CompanyController.java
Add exception handling.

2024-06-18 17:04 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/dto/CompanyDTO.java
> +@Getter
Change Setter and Getter by @Data, also add @Builder and then rewrite code to using this builder.

2024-06-18 17:04 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +    @Column()
Delete all not using brackets

2024-06-19 06:33 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/CompanyController.java
> +@RequestMapping("/company")
The plural form for endpoint names

Link to read: https://www.linkedin.com/advice/3/what-best-practices-naming-restful-api-endpoints#:~:text=the%20resource%20type.-,For%20example%2C%20%2Fusers%2C%20%2Fproducts%2C%20%2Fposts%2C,bad%20examples%20of%20singularized%20endpoints.

2024-06-19 06:34 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/CompanyController.java
> +    public CompanyController(CompanyService companyService) {
Let's use Lombok for injecting

2024-06-19 06:41 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +import jakarta.persistence.*;
Please set up your IDEA to not use wildcard imports and share with your team in chat how to do it

2024-06-19 06:43 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/exception/GlobalExceptionHandler.java
> +@ControllerAdvice
Should be `@RestControllerAdive`

2024-06-19 06:45 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleResponseStatusException(ResponseStatusException ex, WebRequest request) {
Let's create our exception class response and use it instead of the object class

2024-06-19 06:48 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/exception/ResourceNotFoundException.java
> +public class ResourceNotFoundException extends RuntimeException {
Add annotation `@ResponseStatus` with property` value = HtttpStatus.NOT_FOUND`

2024-06-19 06:50 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/mapper/CompanyMapper.java
> +public interface CompanyMapper {
Add annotation `@Mapper` here.

2024-06-19 06:51 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +    private Integer id;
Why Integer?

2024-06-19 07:31 UTC, SavaLX commented on README.md
> +User Name: sa
Remove

2024-06-19 08:12 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Do you need to provide a strategy here?

2024-06-19 08:13 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +@Table(name = "COMPANY")
The table's name must be in lower case

2024-06-19 08:15 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/CompanyController.java
> +@RequestMapping("/company")
Add versioning to the path as well
`/v1/companies`

2024-06-19 08:17 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/CompanyController.java
> +    public CompanyEntity createCompany(@RequestBody CompanyEntity company) {
Use DTOs instead of Entities for public API

2024-06-19 08:17 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
> +  public ExampleEntity createExample(@RequestBody ExampleEntity example) {
There are different approaches to using DTOs and Entities, but one of the main rule - the Client shouldn't receive and send Entities.

As we are using one DTOs type in our app, let's change parameter to DTO instead of Entity

2024-06-19 08:18 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
> +  public Optional<ExampleEntity> updateExample(@PathVariable Integer id, @RequestBody ExampleEntity example) {
The same rule as mentioned above, change parameter

2024-06-19 08:19 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +    private String status;
Can we use Enum here?

2024-06-19 08:19 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
> +public class ExampleController {
should be removed with your commit as you are adding non-example Controller 
PS: and all related stuff except DB changelog

2024-06-19 08:24 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/CompanyService.java
> +    public CompanyEntity updateCompany(Integer id, CompanyEntity updatedCompany) {
Let's use Mapper for updating entity, to not do it manually

2024-06-19 08:25 UTC, anton-kolyaev requested changes

2024-06-19 08:25 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +    private Integer id;
We haven't discussed that thing, but let use UUIDs as id for all our Entities

2024-06-19 08:25 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/service/CompanyService.java
> +                .map(company -> {
I'm not very familiar with MapStruct but I guess you can use mapper over here. Correct me if I'm wrong @SavaLX

2024-06-19 08:25 UTC, anton-kolyaev commented on src/main/resources/changelog/dml/1_insert_company_table.xml
> +<!--            <insert tableName="company">-->
once you've created changeSet you will not be able to update it in any case. So that's no sence to create one as placeholder

2024-06-19 08:25 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
> +  public List<ExampleEntity> getAllExamples() {
Don't return to Client Entity or Optional, only DTO

2024-06-19 08:36 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerTest.java
> +class CompanyControllerTest {
Just use `@ExtendWith(MockitoExtension.class)` to avoid creating manually mocks

2024-06-19 08:38 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerTest.java
> +        CompanyEntity company =  CompanyEntity.builder()
Look at the EasyRandom for creating objects and get rid of duplicate code

2024-06-19 08:47 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerIntegrationTest.java
> +        CompanyEntity company1 = CompanyEntity.builder()
Use EasyRandom

2024-06-19 08:50 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/CompanyService.java
> +                .map(company -> {
It's right, i left comment also about it

2024-06-20 08:47 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/controller/CompanyController.java
> +@RequestMapping("/company")
Add versions and rename endpoint.

2024-06-20 08:47 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/controller/CompanyController.java
> +    public CompanyController(CompanyService companyService) {
Add Lombok to injecting

2024-06-20 08:47 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +import jakarta.persistence.*;
Add to README file how deactivate wildcard imports.

2024-06-20 08:48 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/exception/GlobalExceptionHandler.java
> +@ControllerAdvice
Rewrite to RestControllerAdive

2024-06-20 08:49 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/exception/ResourceNotFoundException.java
> +public class ResourceNotFoundException extends RuntimeException {
Add this annotation.

2024-06-20 08:49 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/mapper/CompanyMapper.java
> +public interface CompanyMapper {
Add this annotation

2024-06-20 08:49 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +    private Integer id;
Change Integer to UUID.

2024-06-20 08:50 UTC, HotoMazur commented on README.md
> +User Name: sa
Done

2024-06-20 08:50 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
I not need this stratagem, without stratage all works.

2024-06-20 08:51 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +@Table(name = "COMPANY")
Rewrite to lowercase.

2024-06-20 08:51 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/controller/CompanyController.java
> +    public CompanyEntity createCompany(@RequestBody CompanyEntity company) {
Useing DTO in recieve and respond.

2024-06-20 08:52 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
> +  public ExampleEntity createExample(@RequestBody ExampleEntity example) {
Now use DTO in recieve and send.

2024-06-20 08:52 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
> +  public Optional<ExampleEntity> updateExample(@PathVariable Integer id, @RequestBody ExampleEntity example) {
Delete Example.

2024-06-20 08:53 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +    private String status;
Yes, rewrite String Status to Enam.

2024-06-20 08:53 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
> +public class ExampleController {
Delete all Examples

2024-06-20 08:53 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/service/CompanyService.java
> +    public CompanyEntity updateCompany(Integer id, CompanyEntity updatedCompany) {
Done.

2024-06-20 08:54 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/service/CompanyService.java
> +                .map(company -> {
Done.

2024-06-20 08:54 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
> +  public List<ExampleEntity> getAllExamples() {
Delete Examples files,  in Company files all done.

2024-06-20 08:55 UTC, HotoMazur commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerTest.java
> +class CompanyControllerTest {
Add to test.

2024-06-20 08:55 UTC, HotoMazur commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerTest.java
> +        CompanyEntity company =  CompanyEntity.builder()
Add easyRandom.

2024-06-20 08:55 UTC, HotoMazur commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerIntegrationTest.java
> +        CompanyEntity company1 = CompanyEntity.builder()
Done

2024-06-21 06:21 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/constants/Status.java
> +public enum Status {
Too general, the name needs to be clarified

2024-06-21 06:24 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +import jakarta.persistence.*;
I see that you are still using wildcard imports here

2024-06-21 06:30 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/exception/CompanyNotFoundException.java
> +public class CompanyNotFoundException extends RuntimeException {
I believe you don't need to create separate exception classes for all entities.
Let's use the general class for such exception

2024-06-21 06:33 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleResponseStatusException(ResponseStatusException ex, WebRequest request) {
You created a class, but you aren't using it. 
Pay attention to all comments/advices that we provide in the review.

2024-06-21 06:35 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/CompanyService.java
> +    private final CompanyMapper companyMapper = CompanyMapper.INSTANCE;
You already created INSTANCE in the Mapper, use it and don't declare property here

2024-06-21 06:39 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerTest.java
> +    void setUp() {
Initialize the property where it is declared

2024-06-21 06:42 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/CompanyService.java
> +                .orElseThrow(() -> new CompanyNotFoundException("Company with ID " + updatedCompany.getId() + " was not found"));
Extract `updatedCompany.getId()` to local variable to not call 2 times get in the object

2024-06-21 07:15 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/CompanyService.java
> +            company.setId(UUID.randomUUID());
Why do you need to set UUID manually? It should create UUID automatically when the save method is called

2024-06-21 09:48 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/service/CompanyService.java
> +    private final CompanyMapper companyMapper = CompanyMapper.INSTANCE;
Delete companyMapper variable.

2024-06-21 09:48 UTC, HotoMazur commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerTest.java
> +    void setUp() {
Delete SetUp and declare easyRandom above

2024-06-21 09:49 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/service/CompanyService.java
> +                .orElseThrow(() -> new CompanyNotFoundException("Company with ID " + updatedCompany.getId() + " was not found"));
Create companyId variable.

2024-06-21 09:49 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/service/CompanyService.java
> +            company.setId(UUID.randomUUID());
Generate UUID automatically

2024-06-25 07:32 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/CompanyController.java
> +        System.out.println("asd");
Remove it

2024-06-25 16:05 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/entity/CompanyEntity.java
> +import jakarta.persistence.*;
Done

2024-06-25 16:06 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleResponseStatusException(ResponseStatusException ex, WebRequest request) {
Delete useless exception class.

2024-06-25 16:06 UTC, HotoMazur commented on src/main/resources/changelog/dml/1_insert_company_table.xml
> +<!--            <insert tableName="company">-->
Delete insert company file.

2024-06-25 16:06 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/controller/CompanyController.java
> +        System.out.println("asd");
Remove

2024-06-25 20:09 UTC, SavaLX approved these changes

2024-06-26 05:50 UTC, NormantasN approved these changes

2024-06-26 07:51 UTC, anton-kolyaev commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerTest.java
> +import static org.mockito.Mockito.*;
avoid wildcards please

2024-06-26 07:56 UTC, anton-kolyaev commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerTest.java
> +        CompanyDTO createdCompanyDTO = companyController.createCompany(newCompanyDTO);
Lets user MockMVC instead https://spring.io/guides/gs/testing-web

2024-06-30 10:50 UTC, HotoMazur commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerTest.java
> +        CompanyDTO createdCompanyDTO = companyController.createCompany(newCompanyDTO);
Done

2024-06-30 10:50 UTC, HotoMazur commented on src/test/java/com/coherentsolutions/pot/insurance/company/CompanyControllerTest.java
> +import static org.mockito.Mockito.*;
Done

2024-07-01 05:41 UTC, anton-kolyaev approved these changes
resolve conflicts, ping me if need in reapprove after

2024-07-01 09:58 UTC, merged