Feature/lji 6 employe mvc
Java-POT-Summer-24/pot-java-summer-24 pull request #17
Opened 2024-06-26 06:59 UTC by Cioperis

Added employee mvc template
Added some methods to add an employee, update, delete, get all employees.
Data validation to be added and tests

2024-06-27 08:36 UTC, anton-kolyaev requested changes

2024-06-27 08:36 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +        return EmployeeDTO.builder()
You've added mappers to convert dto to entity and back. Do you still need in manual remapping?

2024-06-27 08:36 UTC, anton-kolyaev commented on src/main/resources/changelog/changelog-master.xml
> +        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
avoid changes like this (auto format code) on common files - if it's necessary discuss and adjust codestyle for everyone in team

2024-06-27 09:20 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +}
I think we should use soft-delete

2024-06-28 05:22 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/controller/EmployeeController.java
> +@RequestMapping("/v1/employee")
fixed

2024-06-28 05:22 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/entity/EmployeeEntity.java
> +    private String userName; // unique field
fixed

2024-06-28 05:47 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +                .orElse(null);
resolved but i used responsestatusexception here, is that sufficient or should i create and use a custom exception?

2024-06-28 05:55 UTC, Cioperis commented on src/main/resources/changelog/changelog-master.xml
> +        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
reverted and added the closing tab </databaseChangeLog> cause it was missing for some reason

2024-06-28 06:22 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +        return EmployeeDTO.builder()
added proper mapping (not manual) except to update information

2024-06-28 06:28 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +}
fixed

2024-06-30 16:07 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/dto/EmployeeDTO.java
> +    private Integer SSN;
lowercase property name

2024-06-30 16:08 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/repository/EmployeeRepository.java
> +public interface EmployeeRepository extends JpaRepository<EmployeeEntity, UUID>{
@Repository annotation

2024-06-30 16:10 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +    private final EmployeeRepository employeeRepository;
There is no need to inject a mapper, you already have INSTANCe of the mapper

2024-06-30 16:10 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +    private final EmployeeMapper employeeMapper;
There is no need to inject a mapper, you already have INSTANCe of the mapper

2024-06-30 16:13 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +                .map(employee -> {
Use the mapper to update the entity and avoid doing it manually

2024-06-30 16:15 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +                    employee.setDeleted(true);
Do we need to have such property or can we add status for employees and set it to "INACTIVE"?

2024-06-30 16:17 UTC, SavaLX commented on src/main/resources/changelog/changelog-master.xml
Where is your changeset with creating the Employee table and inserting some data into the Database?

2024-07-01 05:17 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/dto/EmployeeDTO.java
> +    private Integer SSN;
fixed

2024-07-01 05:18 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/repository/EmployeeRepository.java
> +public interface EmployeeRepository extends JpaRepository<EmployeeEntity, UUID>{
fixed

2024-07-01 05:31 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +    private final EmployeeMapper employeeMapper;
instance is now used

2024-07-01 05:31 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +                .map(employee -> {
manual mapping removed

2024-07-01 06:16 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +                .orElse(null);
changed to reuse existing exceptions

2024-07-01 06:16 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +                    employee.setDeleted(true);
updated to use enum inactive status instead

2024-07-01 06:35 UTC, Cioperis commented on src/main/resources/changelog/changelog-master.xml
resolved

2024-07-01 07:23 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +        return EmployeeDTO.builder()
update information was changed too to not use manual remapping

2024-07-01 08:53 UTC, anton-kolyaev requested changes

2024-07-01 08:53 UTC, anton-kolyaev commented on src/test/java/com/coherentsolutions/pot/insurance/claim/EmployeeControllerTest.java
> +class EmployeeControllerTest {
Use mockMVC to implement integration tests and lets write unit tests for something meaningful

2024-07-01 08:53 UTC, anton-kolyaev commented on src/main/resources/changelog/ddl/4_create_employees_table.xml
> +            employee_id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
will RANDOM_UUID() work on Postgres?

2024-07-01 08:53 UTC, anton-kolyaev commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter'
were there any reasonable updates in this file?

2024-07-01 09:54 UTC, Cioperis commented on src/main/resources/changelog/ddl/4_create_employees_table.xml
> +            employee_id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
it works with 'uuid-ossp' extension enabled + claims use random_uuid()

2024-07-01 10:20 UTC, Cioperis commented on build.gradle
> +  testImplementation 'com.h2database:h2:1.3.148'
done

2024-07-01 10:21 UTC, Cioperis commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter'
there weren't. i needed to rebuild the project in gradle menu but i tried implementing other dependencies here. unnecessary/removed.

2024-07-01 11:05 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/EmployeeController.java
> +    @DeleteMapping("/{employeeId}/deactivate")
need not in` /deactivate` suffix your final REST will be read as
```
DELETE employees {with given ID}
```

2024-07-01 11:11 UTC, anton-kolyaev requested changes

2024-07-01 11:11 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/entity/EmployeeEntity.java
> +import jakarta.persistence.*;
replace wildcard with explicit imports

2024-07-01 11:25 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/entity/EmployeeEntity.java
> +import jakarta.persistence.*;
replaced

2024-07-01 11:33 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/controller/EmployeeController.java
> +    @DeleteMapping("/{employeeId}/deactivate")
fixed

2024-07-01 13:25 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/EmployeeController.java
> +    @DeleteMapping("/{employeeId}")
HttpStatus.NO_CONTENT if you return void

2024-07-01 13:26 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/EmployeeController.java
> +        return employeeService.updateEmployee(employeeId, updatedEmployeeDTO);
use appropriate response statuses as here
https://github.com/Java-POT-Summer-24/pot-java-summer-24/pull/19/files#diff-2a7b45711279412c3107b85210cb9da296ddf6520c76e837e68641d5d48c55ccR19

2024-07-01 14:06 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/controller/EmployeeController.java
> +        return employeeService.updateEmployee(employeeId, updatedEmployeeDTO);
done

2024-07-01 14:07 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/controller/EmployeeController.java
> +    @DeleteMapping("/{employeeId}")
void is returned so corresponding responsestatus is added

2024-07-01 14:09 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/controller/EmployeeController.java
> +import org.springframework.web.bind.annotation.*;
fixed wildcard

2024-07-01 14:09 UTC, Cioperis commented on src/test/java/com/coherentsolutions/pot/insurance/claim/EmployeeControllerTest.java
> +class EmployeeControllerTest {
done

2024-07-01 15:12 UTC, anton-kolyaev approved these changes

2024-07-01 18:21 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/EmployeeEntity.java
> +    private Integer phoneNumber;
I guess storing phone number as String makes work with it more flexible

2024-07-01 18:22 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/mapper/EmployeeMapper.java
> +    void updateEmployeeFromDTO(EmployeeDTO dto, @MappingTarget EmployeeEntity entity);
ignore id?

2024-07-01 18:23 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +                .employeeToEmployeeDTO(employeeRepository.save(EmployeeMapper.INSTANCE.employeeDTOToEmployee(employeeDTO)));
I would suggest you keep saving-converting-converting operations separately for better readability

2024-07-01 19:20 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/entity/EmployeeEntity.java
> +    private Integer phoneNumber;
done

2024-07-01 19:20 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/entity/EmployeeEntity.java
> +    private UUID employeeId;
done

2024-07-01 19:28 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +                .employeeToEmployeeDTO(employeeRepository.save(EmployeeMapper.INSTANCE.employeeDTOToEmployee(employeeDTO)));
unsure if i understood on how to properly do it, did some readability improvements

2024-07-01 19:29 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/mapper/EmployeeMapper.java
> +    void updateEmployeeFromDTO(EmployeeDTO dto, @MappingTarget EmployeeEntity entity);
fixed

2024-07-02 06:45 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/EmployeeEntity.java
> +    private UUID employeeId;
I meant to extend from BaseEntity which already has ID property

2024-07-03 05:09 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/entity/EmployeeEntity.java
> +    private UUID employeeId;
fixed it now

2024-07-03 06:25 UTC, SavaLX approved these changes

2024-07-03 06:28 UTC, anddevdev approved these changes

2024-07-03 06:30 UTC, merged