Feature/LJI-11-plans-mvc
Java-POT-Summer-24/pot-java-summer-24 pull request #19
Opened 2024-06-26 22:27 UTC by NormantasN

LJI-11 task. Create mvc for plans: implement plan entity, mapper and dto. Implement controller with exception handling, data and service layers. Add liquibase script to create and add data to the table. Add unit and integration tests for plans.

2024-06-27 08:47 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
Do we need to specify "allPlans" in @GetMapping and "add" in @PostMapping? I think they can be omitted.

2024-06-27 08:52 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
I think adding a GlobalExceptionHandler will be beneficial for exception handling, and try-catch blocks can be ommitted here if it will be added.

2024-06-27 09:17 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
> +    }
I think client should be sending the id of entity to update to service.

2024-06-27 14:42 UTC, anton-kolyaev commented on .idea/.name
> +insurance
please add all files under `.idea` directory to gitignore and remove it from commit

2024-06-27 14:51 UTC, anton-kolyaev requested changes

2024-06-27 14:51 UTC, anton-kolyaev commented on build/generated/sources/annotationProcessor/java/main/com/coherentsolutions/pot/insurance/mapper/PlanMapperImpl.java
add `out`, `build`, `target` and all generated stuff to gitignore

2024-06-27 21:52 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
Omitted

2024-06-30 19:14 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
Added GlobalExceptionHandler, omitted try-catch blocks

2024-06-30 19:15 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
> +    }
Done

2024-06-30 19:15 UTC, NormantasN commented on .idea/.name
> +insurance
Done

2024-06-30 19:15 UTC, NormantasN commented on build/generated/sources/annotationProcessor/java/main/com/coherentsolutions/pot/insurance/mapper/PlanMapperImpl.java
Done

2024-07-01 07:15 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +    public ResponseEntity<PlanDTO> addPlan(PlanDTO planDTO) {
Service should return DTO, not a ResponseEntity

2024-07-01 07:18 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerTest.java
> +@ExtendWith(MockitoExtension.class)
Is it a unit test? If yes, maybe then it should test the service class. 
If you want to write a integration test, then you have to use WebMvcTest and test only api

2024-07-01 10:46 UTC, NormantasN commented on build/generated/sources/annotationProcessor/java/main/com/coherentsolutions/pot/insurance/mapper/PlanMapperImpl.java
Temporarily removed the .idea entry from .gitignore, re-added removed files to git, removed files from Git Tracking, commited changes, re-added .idea entry in .gitignore

2024-07-01 10:46 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +    public ResponseEntity<PlanDTO> addPlan(PlanDTO planDTO) {
Done

2024-07-01 11:20 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
> +        return ResponseEntity.ok(planService.getAllPlans());
Use `
@ResponseStatus(HttpStatus.OK)`
with apropriate http status for all endpoints

2024-07-01 11:23 UTC, anton-kolyaev requested changes

2024-07-01 11:23 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/entity/PlanEntity.java
> +import lombok.*;
replace wildcard

2024-07-01 11:23 UTC, anton-kolyaev commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerTest.java
> +    void testDeactivatePlan() {
add negative case (check that your app throws NotFoundException) as well

2024-07-01 11:57 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/entity/PlanEntity.java
> +import lombok.*;
Done

2024-07-01 11:58 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
> +        return ResponseEntity.ok(planService.getAllPlans());
Done

2024-07-01 13:09 UTC, NormantasN commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerTest.java
> +    void testDeactivatePlan() {
Done

2024-07-01 13:11 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
> +    @ResponseStatus(HttpStatus.OK)
NO_CONTENT if you return void

2024-07-01 13:29 UTC, anton-kolyaev commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerTest.java
> +@ExtendWith(MockitoExtension.class)
Still need in integration tests

2024-07-01 13:33 UTC, anton-kolyaev commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerTest.java
> +            verify(planService).deactivatePlan(nonExistentId);
https://www.baeldung.com/mockito-exceptions

2024-07-01 16:04 UTC, NormantasN commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerTest.java
> +@ExtendWith(MockitoExtension.class)
> Is it a unit test? If yes, maybe then it should test the service class. If you want to write a integration test, then you have to use WebMvcTest and test only api

It is a unit test class for PlanController class as it mocks the PlanService and verifies the interactions between the controller and the service. I added an integration tests class for the controller as well

2024-07-01 16:30 UTC, NormantasN commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerTest.java
> +            verify(planService).deactivatePlan(nonExistentId);
Done

2024-07-01 17:59 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerTest.java
> +@ExtendWith(MockitoExtension.class)
@NormantasN I would recommend having unit tests for the service layer and integration tests for the controller layer.

2024-07-01 18:02 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
> +    private final PlanService planService;
add blank lines above and below to separate property, class and method declarations

2024-07-01 18:04 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/PlanEntity.java
> +    private UUID planId;
you have [BaseEntity] class for it

2024-07-01 18:08 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +    private final PlanRepository planRepository;
separate the declarations and check if is google style is active in your IDEA

2024-07-01 18:14 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +            UUID planId = planDTO.getPlanId();
It's strange to check the entity's existence in the database as this API should be used only for creating a plan. You will get NPE here as the client won't send you Dto with ID

2024-07-01 18:19 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
> +    public PlanDTO updatePlan(@Valid @RequestBody PlanDTO planDTO){
I would expect to receive the ID as a pathVariable to update the particular plan

2024-07-01 22:29 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +    private final PlanRepository planRepository;
![Capture](https://github.com/Java-POT-Summer-24/pot-java-summer-24/assets/80217309/6d81bc46-be8e-4a31-880c-e0602ba9b0d1)
Done, it is enabled, I have imported it

2024-07-01 22:29 UTC, NormantasN commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerTest.java
> +@ExtendWith(MockitoExtension.class)
Done

2024-07-01 22:29 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
> +    private final PlanService planService;
Done

2024-07-01 22:30 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/entity/PlanEntity.java
> +    private UUID planId;
Edited to inherit from BaseEntity

2024-07-01 22:55 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +            UUID planId = planDTO.getPlanId();
Fixed

2024-07-01 23:23 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
> +    public PlanDTO updatePlan(@Valid @RequestBody PlanDTO planDTO){
Fixed

2024-07-02 06:56 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
> +        planDTO.setPlanId(id);
There is no need to set the id to dto as in service you will get it again from dto. 
Also, you will use the update method of the mapper to update the entity and in this method, the 'ID' is ignored.
I would recommend you just pass the ID to the service

2024-07-02 13:51 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/controller/PlanController.java
> +        planDTO.setPlanId(id);
Done

2024-07-02 14:01 UTC, SavaLX approved these changes

2024-07-02 14:35 UTC, merged