Feature/LJI-19-claims-filters
Java-POT-Summer-24/pot-java-summer-24 pull request #20
Opened 2024-06-28 09:50 UTC by anddevdev

This PR introduces the following features for the Claims:

1. Filtering claims:
- Allows filtering of claims by claim number, consumer (employee), employer (company), and status.
- Multiple filters can be applied simultaneously (filter by company and status at the same time).

2. Sorting claims:
- Enables sorting of claims by claim number, consumer, employer, date of service, plan, amount, and status(Ascending and descending orders)
- Default sorting is enabled by date of service in descending order (newest claims first).

3. Pagination 
- Default pagination is set to 10 entities per page

4. New endpoint:
- Added a new endpoint /v1/claims/filtered for handling filtered, sorted, and paginated requests.
- Added new requests to Claims collection in Postman to test the added features.

2024-07-01 15:42 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ClaimController.java
> +    int pageSize = pageable.getPageSize() == 20 ? 10 : pageable.getPageSize();
(⊙ _ ⊙ )

2024-07-01 15:57 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ClaimController.java
> +    int pageSize = pageable.getPageSize() == 20 ? 10 : pageable.getPageSize();
Deleted, just set the page size to 10

2024-07-01 17:01 UTC, anton-kolyaev requested changes

2024-07-01 17:01 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/service/ClaimService.java
> +    if (filterCriteria.getClaimNumber() != null && !filterCriteria.getClaimNumber().isEmpty()) {
can we do any refactoring to make it "prettier"?

2024-07-01 17:27 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ClaimController.java
> +    return ResponseEntity.ok(claimsPage);
Done

2024-07-02 13:11 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/specifications/SortCriteria.java
> +public class SortCriteria {
Could we keep sorting in the Pageable object and do not create our custom class?

2024-07-02 13:14 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/specifications/FilterAndSortCriteria.java
> +  private FilterCriteria filterCriteria;
What if make it more abstract to re-use it with other controllers?
I mean: receive Filters as a list with the field name and value of this field?

2024-07-02 13:17 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ClaimController.java
> +    FilterCriteria filterCriteria;
Maybe it's better to move this logic to the service layer, what do you think?

2024-07-03 07:16 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/specifications/FilterAndSortCriteria.java
> +  private FilterCriteria filterCriteria;
Let's leave it for now

2024-07-03 07:35 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/specifications/SortCriteria.java
> +public class SortCriteria {
Done

2024-07-03 07:36 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ClaimController.java
> +    FilterCriteria filterCriteria;
Done

2024-07-03 10:28 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/service/ClaimService.java
> +  private Specification<ClaimEntity> buildSpecification(ClaimFilterCriteria claimFilterCriteria) {
Done

2024-07-03 10:31 UTC, SavaLX approved these changes

2024-07-04 09:26 UTC, anton-kolyaev submitted a review, later dismissed
Add integration test(s) please

2024-07-08 13:56 UTC, NormantasN approved these changes

2024-07-08 17:52 UTC, merged