Feature/LJI-18-plans-filters
Java-POT-Summer-24/pot-java-summer-24 pull request #27
Opened 2024-07-04 22:53 UTC by NormantasN

This PR introduces the following features for the Plans:

1. Filtering plans allow filtering by plan name, status, plan type and also multiple filters (e.g filter by name and status at the same time)

2. Sorting plans allow sorting by default (by name), by type or status, ascending or descending

3. Pagination - 10 entities on a page by default

4. New endpoint:
- /v1/plans/filtered for handling filtered, sorted, and paginated requests
- Postman requests
- Unit and integration tests

2024-07-05 10:20 UTC, SavaLX requested changes

2024-07-05 10:20 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanServiceTest.java
> +    assert result != null;
```suggestion
    assertNotNull(result);
```

2024-07-05 10:20 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanServiceTest.java
> +    when(planService.addPlan(any(PlanDTO.class))).thenReturn(newPlanDTO);
This test class is created for test service, but you mocked it. 
Please reformat your test class fully to test in the right way your service

2024-07-05 10:20 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerIntegrationTest.java
> +  public void testGetFilteredSortedPlans() throws Exception {
Please reformat fully your test class regarding this comment - https://github.com/Java-POT-Summer-24/pot-java-summer-24/pull/24#discussion_r1665361282

2024-07-05 15:17 UTC, NormantasN commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanServiceTest.java
> +    assert result != null;
Done

2024-07-05 15:27 UTC, NormantasN commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanServiceTest.java
> +    when(planService.addPlan(any(PlanDTO.class))).thenReturn(newPlanDTO);
How should I test it without using Mockito.when?

2024-07-07 20:13 UTC, NormantasN commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanServiceTest.java
> +    when(planService.addPlan(any(PlanDTO.class))).thenReturn(newPlanDTO);
Done

2024-07-07 23:31 UTC, NormantasN commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerIntegrationTest.java
> +  public void testGetFilteredSortedPlans() throws Exception {
Done

2024-07-08 09:29 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanServiceTest.java
> +  private PlanService planService;
As discussed in the stand-up, mock the rep layer and unit test the service layer(business logic)

2024-07-08 09:30 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanServiceTest.java
> +    when(planService.addPlan(any(PlanDTO.class))).thenReturn(newPlanDTO);
As discussed in the stand-up, mock the rep layer and unit test the service layer(business logic). Use @ExtendWith(MockitoExtension.class)

2024-07-08 09:31 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerIntegrationTest.java
> +  public void testGetFilteredSortedPlans() throws Exception {
See my example of an Integration test with a mocking rep layer  in the chat

2024-07-08 13:53 UTC, NormantasN commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerIntegrationTest.java
> +  public void testGetFilteredSortedPlans() throws Exception {
Fixed

2024-07-08 13:53 UTC, NormantasN commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanServiceTest.java
> +    when(planService.addPlan(any(PlanDTO.class))).thenReturn(newPlanDTO);
Fixed

2024-07-08 17:38 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerIntegrationTest.java
>  public class PlanControllerIntegrationTest {
Redundant 'Controller' word in the name

2024-07-08 17:45 UTC, NormantasN commented on src/test/java/com/coherentsolutions/pot/insurance/plan/PlanControllerIntegrationTest.java
>  public class PlanControllerIntegrationTest {
Done

2024-07-08 17:48 UTC, SavaLX approved these changes

2024-07-08 18:34 UTC, anddevdev approved these changes

2024-07-08 18:40 UTC, merged