Lji 16 employee filters
Java-POT-Summer-24/pot-java-summer-24 pull request #28
Opened 2024-07-05 01:48 UTC by Cioperis

1. added employee filtering by first name, last name, user name, ssn, date of birth and status
2. default sorting by date of birth
3. added a validation check tool (if entity is null, empty)
4. new endpoint /filtered
5. new postman collection
6. added /filtered tests
7. deleted duplicate employee tables

2024-07-05 09:59 UTC, SavaLX commented
The branch's name should start from feature/, bugfix/, hotfix/, etc.

2024-07-05 10:28 UTC, SavaLX commented
Cover new features by unit-tests

2024-07-05 10:28 UTC, SavaLX requested changes

2024-07-05 10:28 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/EmployeeController.java
> +    public Page<EmployeeDTO> filterAndSortEmployees(
Let's use the same approach in the naming of controllers method
```suggestion
    public Page<EmployeeDTO> getFilteredSortedEmployees(
```

2024-07-05 10:28 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +    private Specification<EmployeeEntity> buildSpecification(EmployeeFilterCriteria employeeFilterCriteria) {
Move private methods to the bottom

2024-07-05 10:28 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/employee/EmployeeControllerTest.java
> +  void testFilterAndSortEmployees() throws Exception {
Please reformat fully your test class regarding this comment - https://github.com/Java-POT-Summer-24/pot-java-summer-24/pull/24#discussion_r1665361282

2024-07-09 05:27 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/controller/EmployeeController.java
> +    public Page<EmployeeDTO> filterAndSortEmployees(
updated namings

2024-07-09 06:35 UTC, Cioperis commented on src/test/java/com/coherentsolutions/pot/insurance/employee/EmployeeControllerTest.java
> +  void testFilterAndSortEmployees() throws Exception {
fully updated tests class

2024-07-09 07:22 UTC, SavaLX commented on src/test/java/com/coherentsolutions/pot/insurance/employee/EmployeeControllerTest.java
> +  void testFilterAndSortEmployees() throws Exception {
Please take a look at this PR - https://github.com/Java-POT-Summer-24/pot-java-summer-24/pull/26/files#diff-5f4041addff00595da8b10f7e613a5f6c0bf7a553c06f632be1679f1e8a9f636 .
There are examples of unit and integration tests

2024-07-09 07:22 UTC, SavaLX commented
Fix build

2024-07-09 10:14 UTC, NormantasN commented on src/main/resources/changelog/dml/6_insert_employees_table.xml
> +      ('d5e38eb0-58a3-4a0f-878c-72eac1877d5e', 'John', 'Doe', 'johndoe', 'john.doe@example.com', '1980-01-01', '123456789', '1234567890', 'ACTIVE'),
Refer to [#26 (comment)](https://github.com/Java-POT-Summer-24/pot-java-summer-24/pull/26#discussion_r1665848645)

2024-07-10 05:40 UTC, Cioperis commented on src/main/resources/changelog/dml/6_insert_employees_table.xml
> +      ('d5e38eb0-58a3-4a0f-878c-72eac1877d5e', 'John', 'Doe', 'johndoe', 'john.doe@example.com', '1980-01-01', '123456789', '1234567890', 'ACTIVE'),
Done

2024-07-10 05:45 UTC, closed without merging