Feature/LJI-28-configure-postgres
Java-POT-Summer-24/pot-java-summer-24 pull request #34
Opened 2024-07-11 22:47 UTC by NormantasN

This PR introduces the following features:
1. Different profiles to run the project:
With docker-compose and other .yml configurations we can now run the application in different profiles - development (PostgreSQL) and production (H2) simultaneously on different ports or separately.
2. Made corrections to the changelogs. Since H2 is using random_uuid() and postgres is using gen_random_uuid(), each database now has its own folder for the table creations.

2024-07-15 06:50 UTC, SavaLX commented on src/main/resources/application-dev.yml
> +server:
It seems like you can move it to the global settings:

```
server:
  error:
    include-message: always
    include-binding-errors: always
    port: 8080
```

2024-07-15 07:55 UTC, NormantasN commented on src/main/resources/application-dev.yml
> +server:
Done

2024-07-16 06:23 UTC, SavaLX approved these changes

2024-07-16 19:03 UTC, SavaLX requested changes

2024-07-16 19:03 UTC, SavaLX commented on src/main/resources/application-dev.yml
> +    change-log: classpath:changelog/changelog-master.xml
As we have one master file for the both profiles, than it's also can be moved to the main property file

2024-07-16 19:03 UTC, SavaLX commented on src/main/resources/changelog/dml/5_insert_plans_table.xml
> +          INSERT INTO plan (plan_name, status, plan_type, start_date, end_date)
As we mentioned with Anton at the start of our training, don't edit the created changelogs, you have to create new changelogs to edit your database

2024-07-17 05:36 UTC, NormantasN commented on src/main/resources/application-dev.yml
> +  data:
Done

2024-07-17 05:36 UTC, NormantasN commented on src/main/resources/application-dev.yml
> +    change-log: classpath:changelog/changelog-master.xml
Done

2024-07-17 05:36 UTC, NormantasN commented on src/main/resources/changelog/dml/5_insert_plans_table.xml
> +          INSERT INTO plan (plan_name, status, plan_type, start_date, end_date)
Done

2024-07-17 06:47 UTC, Cioperis approved these changes

2024-07-17 07:27 UTC, SavaLX commented
The same as in this PR https://github.com/Java-POT-Summer-24/pot-java-summer-24/pull/35#issuecomment-2232614725

2024-07-17 09:25 UTC, NormantasN commented
> The same as in this PR [#35 (comment)](https://github.com/Java-POT-Summer-24/pot-java-summer-24/pull/35#issuecomment-2232614725)

Pinged a question

2024-07-18 07:35 UTC, SavaLX commented on src/main/resources/application.yml
> +    port: 8080
I guess should be on the same level as error

2024-07-18 07:38 UTC, NormantasN commented on src/main/resources/application.yml
> +    port: 8080
Done

2024-07-18 07:54 UTC, SavaLX approved these changes

2024-07-18 08:09 UTC, merged