Feature/LJI-35-configure-redis
Java-POT-Summer-24/pot-java-summer-24 pull request #35
Opened 2024-07-12 18:28 UTC by NormantasN

Added redis configuration to docker-compose, created RedisConfig

2024-07-14 18:04 UTC, anddevdev approved these changes

2024-07-15 06:38 UTC, SavaLX commented
Let's wait until the 31 PR will be merged

2024-07-15 09:12 UTC, anddevdev reviewed
Can we also add keycloak configuration?

2024-07-15 09:27 UTC, SavaLX commented
@anddevdev  it would be the new task with separate ticket for the next sprint
@NormantasN Don't add keycloak to this PR

2024-07-15 09:29 UTC, NormantasN commented
> @anddevdev it would be the new task with separate ticket for the next sprint @NormantasN Don't add keycloak to this PR

I think I have to because keycloak is already merged and to solve conflicts to merge I need to add keycloak

2024-07-15 09:32 UTC, SavaLX commented
@NormantasN So yes, I meant you don't need to add docker configuration for keycloak, but add already existing config you should

2024-07-16 18:50 UTC, SavaLX requested changes

2024-07-16 18:50 UTC, SavaLX commented on docker-compose.yml
> +  redis:
Let's give the names to all containers

2024-07-16 18:50 UTC, SavaLX commented on docker-compose.yml
> +      REDIS_PASSWORD: yourpassword
Let's leave the password here, but FYI it's a bad and dangerous practice

2024-07-16 18:50 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/RedisConfig.java
> +public class RedisConfig {
Take a look at #38

2024-07-16 18:50 UTC, SavaLX commented on src/main/resources/application-prod.yml
> +    redis:
As I see we have the same settings for both profiles, it may be better to extract it into one file.

2024-07-17 06:28 UTC, NormantasN commented on docker-compose.yml
> +  redis:
Done

2024-07-17 06:28 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/RedisConfig.java
> +public class RedisConfig {
Added additional configuration

2024-07-17 06:28 UTC, NormantasN commented on src/main/resources/application-prod.yml
> +    redis:
Done

2024-07-17 07:22 UTC, SavaLX approved these changes

2024-07-17 07:25 UTC, SavaLX commented
Your PR doesn't use the pipeline check, please add it and after successfully passing the build pipeline you will able to merge it

2024-07-18 07:57 UTC, merged