Feature/LJI-33-microservice-for-notifications
Java-POT-Summer-24/pot-java-summer-24 pull request #36
Opened 2024-07-15 06:56 UTC by Cioperis

Added a separate application within an existing one for notification service
Rest communication added (post to send emails)
The logic is not fully added yet (upon deactivation of user/claims) but will be added shortly after investigating if the app structure is sufficient
Contents of email are in application.yml

2024-07-17 19:33 UTC, SavaLX commented
This microservice project is in the src directory, but it should be as a separate directory

2024-07-17 20:03 UTC, SavaLX requested changes

2024-07-17 20:03 UTC, SavaLX commented on src/microservice/src/main/java/com/coherentsolutions/pot/insurance/controller/NotificationController.java
> +public class NotificationController {
In the future we can use this service for other notification ways. Let's rename the basic url

2024-07-17 20:03 UTC, SavaLX commented on src/microservice/src/main/java/com/coherentsolutions/pot/insurance/controller/NotificationController.java
> +  @Autowired
Lombok instead of it

2024-07-17 20:03 UTC, SavaLX commented on src/microservice/src/main/java/com/coherentsolutions/pot/insurance/service/NotificationService.java
> +  @Autowired
Lombok

2024-07-18 15:17 UTC, Cioperis commented on src/microservice/src/main/java/com/coherentsolutions/pot/insurance/NotificationsMicroserviceApplication.java
> +public class NotificationsMicroserviceApplication {
done

2024-07-18 15:40 UTC, Cioperis commented on src/microservice/gradle/wrapper/gradle-wrapper.properties
> +distributionBase=GRADLE_USER_HOME
done
it was added after the base of project was generated. removed due to it being unnecessary

2024-07-18 15:44 UTC, Cioperis commented on src/microservice/src/main/java/com/coherentsolutions/pot/insurance/controller/NotificationController.java
> +  @Autowired
done

2024-07-18 15:44 UTC, Cioperis commented on src/microservice/src/main/java/com/coherentsolutions/pot/insurance/service/NotificationService.java
> +  @Autowired
done

2024-07-18 15:44 UTC, Cioperis commented on src/microservice/src/main/java/com/coherentsolutions/pot/insurance/controller/NotificationController.java
> +public class NotificationController {
done

2024-07-18 16:01 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +  private final WebClient webClient = WebClient.create();
done

2024-07-18 17:58 UTC, NormantasN approved these changes

2024-07-19 07:23 UTC, SavaLX requested changes

2024-07-19 07:23 UTC, SavaLX commented on src/microservice/.gitignore
> +.gradle
remove it from the file

2024-07-19 07:23 UTC, SavaLX commented on src/microservice/settings.gradle
> +rootProject.name = 'microservice'
notification-microservice

2024-07-22 06:14 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/ClaimService.java
> +    return claimRepository.findAll().stream().map(ClaimMapper.INSTANCE::entityToDto)
done

2024-07-22 11:11 UTC, Cioperis commented on src/microservice/.gitignore
> +.gradle
done

2024-07-22 11:13 UTC, Cioperis commented on src/microservice/settings.gradle
> +rootProject.name = 'microservice'
done

2024-07-22 11:16 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/ClaimService.java
> +      String message = "Dear " + claim.getEmployee().getFirstName() + ",\n\nThe claim with number "
done

2024-07-22 13:09 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/ClaimService.java
> +    EmployeeEntity employee = employeeRepository.findByUserName(claimDTO.getEmployee()).orElseThrow(
inside claimdto employee is stored as the username of employee

2024-07-22 13:16 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/ClaimService.java
> +    return claimRepository.findById(id).map(claim -> {
done

2024-07-22 13:16 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/ClaimService.java
> +    return claims.stream().map(ClaimMapper.INSTANCE::entityToDto).collect(Collectors.toList());
done

2024-07-23 08:12 UTC, SavaLX requested changes

2024-07-23 08:12 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/ClaimService.java
> +    String employeeUserName = claimDTO.getEmployee();
We have to rename the property in the ClaimDTO as it's not an employee, it's an employeeUserName

2024-07-23 08:12 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/util/NotificationUtil.java
> +public class NotificationUtil {
Why did you decide to create a separate config for this class?

2024-07-23 11:04 UTC, Cioperis commented on microservice/.gitignore
renamed to notif-svc

2024-07-23 11:48 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/ClaimService.java
> +    String employeeUserName = claimDTO.getEmployee();
done

2024-07-24 05:01 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/util/NotificationUtil.java
> +public class NotificationUtil {
thought code management would be easier. removed config, made client a component class with webclient directly in it

2024-07-24 06:16 UTC, SavaLX approved these changes

2024-07-24 08:50 UTC, closed without merging