[LJI-42] Implement plan limit calculations
Java-POT-Summer-24/pot-java-summer-24 pull request #39
Opened 2024-07-17 13:25 UTC by anddevdev

Implemented plan limit calculation. Added totalLimit and remainingLimit to plan entity. Remaining limit will be calculated if a claim with status approved is being added, or if existing claim's status is being changed to approved. If the limit is exceeded, a message will be shown.

2024-07-19 08:47 UTC, SavaLX requested changes

2024-07-19 08:47 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/dto/ClaimDTO.java
>    private ClaimPlan plan;
would it be better to name it "planType"?

2024-07-19 08:47 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/ClaimEntity.java
> +  private PlanEntity planId;
misleading name

2024-07-22 08:47 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/dto/ClaimDTO.java
>    private ClaimPlan plan;
Done

2024-07-22 08:47 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/entity/ClaimEntity.java
> +  private PlanEntity planId;
Done, changed plan to planType

2024-07-24 06:33 UTC, SavaLX requested changes

2024-07-24 06:33 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/ClaimEntity.java
> +  private PlanEntity planId;
```suggestion
  private PlanEntity planEntity;
```

2024-07-24 08:01 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/entity/ClaimEntity.java
> +  private PlanEntity planId;
Done

2024-07-25 07:49 UTC, NormantasN approved these changes

2024-07-26 06:18 UTC, SavaLX approved these changes

2024-07-26 07:14 UTC, merged