Feauture/[LJI-43] implement package contribution.
Java-POT-Summer-24/pot-java-summer-24 pull request #41
Opened 2024-07-18 08:18 UTC by HotoMazur

Add the checker to the package contribution. If add a new plan and assign it to a specific package, it checks if we have a contribution for this plan or not.

2024-07-19 08:32 UTC, SavaLX commented
Run pipeline please for your PR

2024-07-19 08:39 UTC, SavaLX requested changes

2024-07-19 08:39 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/repository/PlanRepository.java
> +  List<PlanEntity> findAllByPackageId(PackageEntity packageEntity);
why are you passing the entire entity?

2024-07-19 08:39 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +        planRepository.findAllByPackageId(planEntity.getPackageId()).stream()
find the sum through the SQL and don't fetch all entities

2024-07-19 08:39 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +    PackageEntity packageContribution = packageRepository.findById(planEntity.getPackageId().getId())
The misleading name of the variable

2024-07-19 08:39 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +  private void validateContributionLimit(PlanEntity planEntity) {
Add negative and positive unit tests for this logic

2024-07-19 11:29 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +  private void validateContributionLimit(PlanEntity planEntity) {
Done

2024-07-19 11:29 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +    PackageEntity packageContribution = packageRepository.findById(planEntity.getPackageId().getId())
Done

2024-07-19 11:29 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +        planRepository.findAllByPackageId(planEntity.getPackageId()).stream()
Done

2024-07-19 11:29 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/repository/PlanRepository.java
> +  List<PlanEntity> findAllByPackageId(PackageEntity packageEntity);
Done

2024-07-19 11:55 UTC, HotoMazur commented
@SavaLX, I do not understand, how I can run pipeline by myself. How I understand that we have the triggers in github/workflofs which should start run pipeline, when we create or update pr. So maybe you have some advice?

2024-07-19 13:31 UTC, SavaLX commented
@You have to merge the main branch into your branch

2024-07-24 06:36 UTC, SavaLX requested changes

2024-07-24 06:36 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/entity/PlanEntity.java
> +  private PackageEntity packageId;
The property type is 'PackageEntity', but you named the property packageId. It is a misleading name

2024-07-24 06:36 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/repository/PlanRepository.java
> +  double findSumOfTotalLimitByPackageId(@Param("packageId") UUID packageId);
No need to add @Param

2024-07-24 06:36 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +        planRepository.findSumOfTotalLimitByPackageId(planEntity.getPackageId().getId());
`planEntity.getPackageId().getId()` extract to the local variable

2024-07-24 13:05 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/entity/PlanEntity.java
> +  private PackageEntity packageId;
Done. Rename to packageEntity

2024-07-24 13:05 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/repository/PlanRepository.java
> +  double findSumOfTotalLimitByPackageId(@Param("packageId") UUID packageId);
Delete

2024-07-24 13:05 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/service/PlanService.java
> +        planRepository.findSumOfTotalLimitByPackageId(planEntity.getPackageId().getId());
Create local variable packageId

2024-07-25 06:37 UTC, anton-kolyaev approved these changes

2024-07-25 07:52 UTC, NormantasN approved these changes

2024-07-26 07:58 UTC, SavaLX approved these changes

2024-07-26 11:26 UTC, merged