Feature/lji 33 add notification microservice
Java-POT-Summer-24/pot-java-summer-24 pull request #43
Opened 2024-07-24 10:52 UTC by Cioperis

2024-07-25 06:33 UTC, anton-kolyaev requested changes

2024-07-25 06:33 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/dto/ClaimDTO.java
> +  private String employeeUserName;
that's not ok to update already released API without versioning, is it really necessary? if it is then create a new version for endpoint and a new version of DTO (leave old one for compability)

2024-07-25 06:33 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +          """.formatted(employee.getFirstName());
Looks like constant. 
And we potentially will want to have internatilization/localization (i18n/l10n) - let's discuss on daily meeting

2024-07-25 06:33 UTC, anton-kolyaev commented on notif-svc/src/test/java/com/coherentsolutions/pot/insurance/NotificationsMicroserviceApplicationTests.java
> +	void contextLoads() {
Please add some meaningful integration test

2024-07-25 08:05 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/dto/ClaimDTO.java
> +  private String employeeUserName;
Saulius asked me to update the DTO, do I still need to create a separate one?

2024-07-25 13:05 UTC, Cioperis commented on src/main/java/com/coherentsolutions/pot/insurance/service/EmployeeService.java
> +          """.formatted(employee.getFirstName());
added notic properties

2024-07-26 06:48 UTC, Cioperis commented on notif-svc/src/test/java/com/coherentsolutions/pot/insurance/NotificationsMicroserviceApplicationTests.java
> +	void contextLoads() {
done

2024-07-26 08:00 UTC, anton-kolyaev approved these changes

2024-07-29 05:53 UTC, NormantasN approved these changes

2024-07-29 06:48 UTC, SavaLX approved these changes

2024-07-30 17:48 UTC, merged