[LJI-46] Implemented security strategy for company admin
Java-POT-Summer-24/pot-java-summer-24 pull request #45
Opened 2024-07-26 06:58 UTC by NormantasN

Written simple implementation for security strategy for company admin. Still needs testing and debugging

2024-07-29 06:26 UTC, anton-kolyaev requested changes

2024-07-29 06:26 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/constants/UserRole.java
> +  admin, companyAdmin, user
UPPER_CASE for enums

2024-07-29 06:26 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/entity/UserEntity.java
> +@Table(name = "insuranceUser")
why?

2024-07-29 06:26 UTC, anton-kolyaev commented on src/main/resources/changelog/ddl/h2/7_create_users_table.xml
> +      CREATE TABLE insuranceUser
that's not allowed to edit existing changesets, if you need to alter name of table create a new script with update existing

2024-07-29 06:26 UTC, anton-kolyaev commented on src/main/resources/changelog/ddl/h2/7_create_users_table.xml
> -        authorityId UUID,
same as above - only incremental updates

2024-07-29 06:26 UTC, anton-kolyaev commented on src/main/resources/changelog/ddl/h2/8_create_authorities_table.xml
> -      CREATE TABLE authority
same - create a new changelog with delete/drop table

2024-07-29 22:25 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/constants/UserRole.java
> +  admin, companyAdmin, user
Deleted UserRole

2024-07-29 22:27 UTC, NormantasN commented on src/main/java/com/coherentsolutions/pot/insurance/entity/UserEntity.java
> +@Table(name = "insuranceUser")
"user" is a reserved keyword in many SQL databases so it gives a warning. Not applicable anymore since UserEntity is deleted

2024-07-29 22:28 UTC, NormantasN commented on src/main/resources/changelog/ddl/h2/7_create_users_table.xml
> +      CREATE TABLE insuranceUser
Dropped the table

2024-07-29 22:28 UTC, NormantasN commented on src/main/resources/changelog/ddl/h2/7_create_users_table.xml
> -        authorityId UUID,
Dropped the table

2024-07-29 22:28 UTC, NormantasN commented on src/main/resources/changelog/ddl/h2/8_create_authorities_table.xml
> -      CREATE TABLE authority
Dropped the table

2024-08-01 07:38 UTC, anton-kolyaev approved these changes

2024-08-01 08:53 UTC, anddevdev approved these changes

2024-08-01 09:36 UTC, merged