Create login security functional.
Java-POT-Summer-24/pot-java-summer-24 pull request #5
Opened 2024-06-13 15:30 UTC by HotoMazur

Create the login functional. 
Add 3 files:
-LoginConfig
-Security config
-AppBasicAuthenticationEntryPoint

To start work, build project to add two new implementation (security and web)
To log in to account go to localhost:8080 and use this data:

username = user
password = password

2024-06-14 07:42 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/LoginControl.java
> +package com.coherentsolutions.pot.insurance;
Please use the right distribution by directories(packages).
Please check this link https://climbtheladder.com/10-java-package-structure-best-practices/ to

2024-06-14 07:43 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/LoginControl.java
> +public class LoginControl {
It's better to rename it to "LoginController"
Don't make class names shorter

2024-06-14 07:43 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/security/SecurityConfig.java
> +        UserDetails user = User
Let's rename it to "admin" and pass "ADMIN_ROLE" to roles as we implementing the admin portal for now

2024-06-14 07:47 UTC, SavaLX commented
For now just leave the name of branch as it is, but for future add jira ticket number to the name of branch and also to the initial commit.
At this moment when you will push your changes after resolving the comments, add jira ticket number to your commit.
And don't forget to delete your old PR

2024-06-14 07:47 UTC, SavaLX requested changes
Request changes

2024-06-14 08:38 UTC, HotoMazur commented
@SavaLX Change all problem that you show. Send new commit with LJI-3 tag.

2024-06-14 13:30 UTC, anddevdev approved these changes

2024-06-17 06:51 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/login/LoginController.java
> +package com.coherentsolutions.pot.insurance.login;
This is one possible strategy for grouping classes into packages (grouping by feature), but I would suggest using grouping by layer. A large application is easier to navigate when classes are grouped into layers. 
Example: all controllers must be in the "controller" package.

2024-06-17 08:43 UTC, HotoMazur commented on src/main/java/com/coherentsolutions/pot/insurance/login/LoginController.java
> +package com.coherentsolutions.pot.insurance.login;
Implement your task. Create controller package and relocate the LoginController to this package. Delete login package.

2024-06-17 08:45 UTC, SavaLX approved these changes

2024-06-17 10:00 UTC, merged