[LJI-7] Implement POC for H2 database.
Java-POT-Summer-24/pot-java-summer-24 pull request #8
Opened 2024-06-17 13:59 UTC by anddevdev

This pull request implements the POC for using the H2 database in our project. It includes the following changes:

1. H2 Database Configuration

Added H2 database configuration to application.yml
Enabled the H2 console for easy database access.

2. Liquibase Configuration

Added Liquibase and other necessary dependencies to build.gradle.
Created Liquibase changelog files to manage database schema changes:

- changelog-master.xml includes changelog-1.0.xml.
- changelog-1.0.xml creates example_table with id and name columns.

3. Example Entity, Repository, Service, and Controller

Entity: Created ExampleEntity with fields id and name.

Repository: Created ExampleRepository interface extending JpaRepository.

Service: Implemented ExampleService with methods for basic CRUD operations:

- addExample()
- getAllExamples()
- updateExample()
- deleteExample()

Controller: Created ExampleController with REST endpoints for CRUD operations:

- POST /examples to add a new example.
- GET /examples to retrieve all examples.
- PUT /examples/{id} to update an existing example.
- DELETE /examples/{id} to delete an example.

4. Spring Security Configuration
Configured Spring Security to allow access to the H2 console.

2024-06-17 17:32 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
> +  public ExampleController(ExampleService exampleService) {
Let's use the power of Lombok - '@RequiredArgsConstructor'

2024-06-17 17:50 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
> +  public ExampleController(ExampleService exampleService) {
Added it in the latest commit

2024-06-17 22:04 UTC, SavaLX requested changes

2024-06-17 22:04 UTC, SavaLX commented on src/main/java/com/coherentsolutions/pot/insurance/repository/ExampleRepository.java
> +public interface ExampleRepository extends JpaRepository<ExampleEntity, Integer> {
`@Repository`

2024-06-18 05:16 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/service/ExampleService.java
> +  public ExampleService(ExampleRepository exampleRepository) {
Used this annotation, and will commit it after resolving all the changes.

2024-06-18 05:21 UTC, anddevdev commented on src/main/resources/changelog/changelog-1.0.xml
We can use the same naming convention wich we use in our branch names. This way, the name of the changelog-1.0.xml will become LJI-7-POC-for-H2.xml. Will this be suitable? Also created separate directories for data manipulation and data  definition scripts. Will include them and a simple data definition script in the next commit.

2024-06-18 05:23 UTC, anddevdev commented on src/main/resources/application.yml
> +    password: password
Used environment variable for password storage. Should i also include a default value for development purposes now like in this example: ${DB_PASSWORD:password}, or just leave it as ${DB_PASSWORD}?

2024-06-18 05:24 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/service/ExampleService.java
> +  public Optional<ExampleEntity> updateExample(Integer id, ExampleEntity updatedExample) {
Used orElseThrow with returning Entity, and will include it in the next commit.

2024-06-18 05:25 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/repository/ExampleRepository.java
> +public interface ExampleRepository extends JpaRepository<ExampleEntity, Integer> {
Added @Repository annotation here.

2024-06-18 05:28 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/security/SecurityConfig.java
> +                .headers(headers -> headers.frameOptions(frameOptions -> frameOptions.sameOrigin()));
Would it be appropriate to define a helper method like this:
`private void configureFrameOptions(HeadersConfigurer<HttpSecurity> headers) {
        headers.frameOptions().sameOrigin();
    }`

And then reference it in SecurityFilterChain like this:
`.headers(this::configureFrameOptions);`?

2024-06-18 05:34 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/entity/ExampleEntity.java
> +  @Column(nullable = false)
Removed the @Column(nullable = false) annotation and will include this change in the next commit.

2024-06-18 08:05 UTC, SavaLX commented on src/main/resources/changelog/changelog-1.0.xml
It's one of the naming patterns, but in our application, it's not needed to keep such a name, because your branch and commit already have the ticket number. Let's use this pattern: indexNumber_actionName_tableName
Example: `1_create_employee` for ddl or `1_insert_employee` for dml

2024-06-18 10:56 UTC, anddevdev commented on src/main/resources/changelog/changelog-1.0.xml
Done

2024-06-18 10:57 UTC, anddevdev commented on src/main/resources/application.yml
> +    password: password
Done, credentials shared in README

2024-06-18 10:57 UTC, anddevdev commented on src/main/java/com/coherentsolutions/pot/insurance/security/SecurityConfig.java
> +                .headers(headers -> headers.frameOptions(frameOptions -> frameOptions.sameOrigin()));
Done

2024-06-19 06:25 UTC, anton-kolyaev commented on src/main/java/com/coherentsolutions/pot/insurance/controller/ExampleController.java
> +  public ExampleEntity createExample(@RequestBody ExampleEntity example) {
We agreed on call with @SavaLX  and teammembers to leave as is for current POC and use DTO-Entity mapping for next implementations

2024-06-19 06:28 UTC, SavaLX commented on src/main/resources/application.yml
> +    password: password
Do you understand why I suggested you remove credentials from the property file?

2024-06-19 06:37 UTC, anddevdev commented on src/main/resources/application.yml
> +    password: password
For security reasons removed password from readme.

2024-06-19 08:08 UTC, SavaLX approved these changes

2024-06-19 08:13 UTC, anton-kolyaev approved these changes

2024-06-19 08:15 UTC, merged